version: '2'
services:
  samba:
    build: ./image
    image: docker-samba:1
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "455:455"
    volumes:
      - /home/karol/samba/:/var/data/smb/
    entrypoint: "/usr/sbin/smbd -FS"
